---
- name: Ensure the selinux packages are installed (<= el7)
  tags: selinux
  become: true
  yum:
    name: "{{ selinux_packages }}"
    state: present
  register: selinux_yum
  vars:
    selinux_packages:
      - libselinux-python
      - selinux-policy
  when: ansible_distribution_major_version|int <= 7

- name: Ensure the selinux packages are installed (>= el8)
  tags: selinux
  become: true
  yum:
    name: "{{ selinux_packages }}"
    state: present
  register: selinux_yum
  vars:
    selinux_packages:
      - python3-libselinux
      - selinux-policy
  when: ansible_distribution_major_version|int >= 8

- name: Applying selinux policy and state configurations
  tags: selinux
  become: true
  selinux:
    conf: "{{ selinux_conf }}"
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  register: selinux_module
  when: selinux_yum is success

- name: Attempting to reboot host, if applicable
  tags: selinux
  become: true
  reboot:
    reboot_timeout: "{{ selinux_reboot_timeout }}"
  when:
    - selinux_module is changed
    - selinux_module.reboot_required|bool
    - selinux_reboot|bool
...
